/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "njuxyqquszfdkeoyizkh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qdXh5cXF1c3pmZGtlb3lpemtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MDA3ODcsImV4cCI6MjA3NzA3Njc4N30.We61-06MPu7JvqIv4QQInTDG-rfsL2VcN0ICHkGivUk"